{{- range $_, $https := .Values.app.ingress.https }}
{{- if eq $https.managedBy "cert-manager" }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ $https.secretName | quote }}
  namespace: istio-system
  labels:
    {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
    {{- with (last $.Values.app.deployments) }}
    {{ $.Values.app.group }}/app-deployment-version: {{ .version | quote }}
    app.kubernetes.io/version: {{ .version | quote }}
    {{- end }}
    app.kubernetes.io/name: {{ $.Values.app.name | quote }}
    app.kubernetes.io/instance: {{ $.Values.app.name | quote }}
    app.kubernetes.io/managed-by: "LensApps"
spec:
  secretName: {{ $https.secretName }}
  secretTemplate:
    labels:
      {{ $.Values.app.group }}/app-name: {{ $.Values.app.name | quote }}
  dnsNames:
    - {{ $https.cname }}
  issuerRef:
    name: {{ $.Values.ingressController.clusterIssuer }}
    kind: ClusterIssuer
---
{{ end }}
{{ end }}
